eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    
microservices:
  vaccination-service:
    endpoints:
      endpoint:
        uri: http://CITIZEN-SERVICE/citizen/id
  citizen-service:
    endpoints:
      endpoint:
        uri: http://VACCINATION-CENTER-SERVICE/add
